### ISSUE TITLE
_customData and waypoint fields causes generated levels to not have notes

### ISSUE THREAD

**Issue by chiacow** [Loloppe/LolighterOld#1]
Steps to reproduce:

1. Open a file.
2. Select 'Light'
3. Select 'Downlight'
4. Save
5. Generated .dat contains _customData and waypoint fields which causes the level to contain no notes when loaded.

Removing these fields causes the level to load properly.

**Comment by Loloppe** [comment]
The .json structure is based on Mediocre Mapper Assistant 2, I've never tried to load in game directly from Lolighter. Usually, people open their maps in an editor, save and then it load properly in game. I'm not sure what to do to fix this issue, as saving a map in an editor would recreate a .json with _customData and _waypoints anyway. Mediocre Mapper Assistant 2 save the map as version 2.2.0, while ChroMapper save as 2.0.0, but I don't think this change anything. Mediocre Mapper Assistant 2 also add a value _BPMChanges and _bookmarks even if it's empty.

**Comment by chiacow** [comment]
Thanks for the quick response Loloppe.

Perhaps it'd be helpful to tell you my use case. I'm using your tool to inject lighting to Beat Sage json files. These files do not have these fields, and adding them seems to break things. You should be able to add a check for Beat Sage as the creator of the level when parsing the level folder and not add those fields in this case.

**Comment by Loloppe** [comment]
Lolighter doesn't read the info.dat file if I remember right, so I can't do that. But I tested it with Beat Sage and it generate a "null" value for both _customData and _waypoints during the opening part (since they don't exist). I can probably fix that by adding a default value.

**Comment by chiacow** [comment]
Sounds good to me. Thanks Loloppe.

**Comment by Loloppe** [comment]
This should be fixed now.

**Comment by chiacow** [comment]
Thanks for being awesome.

**Comment by chiacow** [comment]
Fix worked great. Thanks again.

Do you have a discord? Or contact info? Would like to ask you about something else related to this project if you don't mind.

**Comment by Loloppe** [comment]
My discord is written on the readme: Loloppe#6435
