### ISSUE TITLE
Batch light modification needed

### ISSUE THREAD

**Issue by timoncool** [Loloppe/LolighterOld#2]
Hey! I use Lolighter and this is amazing, thank you very much for this soft.
Can u add batch function for additinoal light show too many files?
I generate 200+ my favorite song on beatsage and all of them no any light, u program crate perfect light. but select and modify files one by one very very long and difficult. 
Please add batch functionality in Lolighter it be cool!

**Comment by Loloppe** [comment]
The new rework of Lolighter can do batch difficulty per song, I won't be releasing more than this.
https://github.com/Loloppe/Lolighter
